---
- hosts: localhost
  gather_facts: false

  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration

  tasks:
  - name: Set AWS region
    set_fact:
      ek_aws_region: "{{ lookup('env', 'AWS_REGION') }}"

  - name: Provision AWS EC2 infrastructure
    block:
    - name: Create a new key pair
      ec2_key:
        name: "ek_{{ ek_config.environment.id }}"
        key_material: "{{ lookup('file', ek_config.ssh.public_key) }}"
        force: false

    - name: Provision placement group
      include_tasks: tasks/create/placement-group.yml
      when: ek_config.params.placementGroup is defined

    - name: Provision security group(s)
      include_tasks: tasks/create/security-groups.yml
      when: (ek_config.params.securityGroups is defined) and (ek_config.params.securityGroups | length > 0)

    - name: Provision instance(s)
      include_tasks: tasks/create/instances.yml

    - name: Provision volume(s)
      include_tasks: tasks/create/volumes.yml
      when: ek_config.params.volumes is defined

    - name: Determine role of instance(s)
      include_tasks: tasks/create/role-tags.yml
      when: ek_config.role is not defined

  - name: Refresh inventory to gather new EC2 instance(s) if any
    meta: refresh_inventory

- hosts: ek_nodeset_{{ hostvars['localhost'].ek_config.environment.nodeset }}
  gather_facts: true

  tasks:
  - name: Enabling support for consistent nvme device mapping
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    include_role:
      name: ekara.nvme

  - name: Make filesystem(s) and mount volume(s)
    include_tasks: tasks/create/filesystems.yml
    when: hostvars['localhost'].ek_ec2_vol_info is defined
