---
- hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration

  tasks:
  - set_fact:
      ekara_env_id: "{{ek_config.environment.name}}_{{ek_config.environment.qualifier}}"
      ekara_nodeset_id: "{{ek_config.environment.name}}_{{ek_config.environment.qualifier}}_{{ek_config.environment.nodeset}}"
      ekara_aws_region: "{{ lookup('env', 'AWS_REGION') }}"

  - debug:
      msg: "ekara_env_id={{ekara_env_id}}"
  - debug:
      msg: "ekara_nodeset_id={{ekara_nodeset_id}}"

  - name: Provision AWS EC2 infrastructure
    block:
    - name: Create a new key pair
      ec2_key:
        name: "ek_{{ekara_env_id}}"
        key_material: "{{ lookup('file', ek_config.connectionConfig.machine_public_key) }}"

    - name: Provision placement group
      include_tasks: tasks/placement-group.yml
      when: ek_config.params.placementGroup is defined

    - name: Provision security group(s)
      include_tasks: tasks/security-groups.yml
      when: (ek_config.params.securityGroups is defined) and (ek_config.params.securityGroups | length > 0)

    - name: Provision instance(s)
      include_tasks: tasks/instances.yml

    - name: Provision volume(s)
      include_tasks: tasks/volumes.yml
      when: ek_config.params.volumes is defined

    - name: Determine role of instance(s)
      include_tasks: tasks/role-tags.yml
      when: ek_config.role is not defined

  - name: Refresh inventory to gather new EC2 instance(s) if any
    meta: refresh_inventory

- hosts: ek_nodeset_{{ hostvars['localhost'].ek_config.environment.nodeset }}
  gather_facts: false

  tasks:
  - name: Make filesystem(s) and mount volume(s)
    include_tasks: tasks/filesystems.yml
    when: hostvars['localhost'].ek_ec2_vol_info is defined
