---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: ekara.configuration
  tasks:
  - set_fact:
      ekara_keypair_name: "{{ekara_configuration_params.environment.name}}_{{ekara_configuration_params.environment.qualifier}}"
      ekara_temp_dir: "tmp-{{lookup('pipe','date') | to_uuid}}"
      ekara_aws_region: "{{ lookup('env', 'AWS_REGION') }}"
      ekara_plf: "{{ekara_configuration_params.environment.name}}_{{ekara_configuration_params.environment.qualifier}}"

  - name: Create temp dir
    file:
      path: "{{ekara_temp_dir}}"
      state: directory
  - name: Create Infrastructure
    block:
    - name: Create a new ec2 key pair
      ec2_key:
        name: "{{ekara_keypair_name}}"
        force: false
        key_material: "{{ lookup('file', ekara_configuration_params.connectionConfig.machine_public_key) }}"

    - name: Provision a set of security groups
      include_tasks: tasks/security-group.yml
      when: ekara_configuration_params.params.security_groups is defined

    - name: Provision a placement group
      include_tasks: tasks/placement-group.yml
      when: ekara_configuration_params.params.placement_group is defined

    - name: Provision a set of instances
      include_tasks: tasks/instances.yml

    - name: Provision volumes
      include_tasks: tasks/volumes.yml
      when: ekara_configuration_params.volumes is defined

    - name: Push outputs to engine
      template:
        src: "templates/output/{{item}}"
        dest: "{{output_dir}}/{{item}}"
      with_items:
      - params.yaml
    always:
    - name: Purge temp dir
      file:
        path: "{{ekara_temp_dir}}"
        state: absent

- name: Create Inventory
  import_playbook: inventory.yml
