---
- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: lagoon.configuration
  tasks:
  - name: Refresh Inventory
    shell: "{{lagoon_configuration_params.component_path.aws}}/inventory/modules/ec2.py --refresh-cache"
    changed_when: false
  - meta: refresh_inventory

  - name: Create inventory folder
    file:
      state: directory
      path: "{{lagoon_inventory_path}}"
  - name: Gather instances
    ec2_instance_facts:
      filters:
        "tag:Name": "{{ lagoon_configuration_params.environment.name }}"
    register: lagoon_instances
  - name: Gather Worker hosts
    ec2_instance_facts:
      filters:
        "tag:Swarm_type": "{{ lagoon_configuration_params.environment.name }}_worker"
        instance-state-name: running
    register: lagoon_workers
  - name: Update local inventory
    template:
      src: templates/hosts.j2
      dest: "{{lagoon_inventory_path}}/hosts"

  - name: Check IP configuration
    set_fact:
      lagoon_public_ip: "{{ lagoon_configuration_params.params.assign_public_ip | default(True) }}"
  - name: Add ssh configuration for each instance
    include_role:
      name: lagoon.ssh
    vars:
      lagoon_ssh_proxy:
      lagoon_ssh_key: "{{ lagoon_configuration_params.connectionConfig.machine_private_key }}"
      lagoon_ssh_host: "{{item.private_ip_address}}"
    when:
    - lagoon_public_ip == False
    - item.state.code != 48
    with_items:
    - "{{ lagoon_instances.instances }}"
    loop_control:
      label: "{{ item.instance_id }}"
