---
- src: https://github.com/ekara-platform/ansible-role-configuration.git
  version: alpha1
  name: ekara.configuration

- src: https://github.com/ekara-platform/ansible-role-ssh-config.git
  version: alpha2
  name: ekara.ssh
