---
- src: https://github.com/tbouvet/ansible-role-configuration.git
  version: ekara
  name: ekara.configuration

- src: https://github.com/tbouvet/ansible-role-ssh-config.git
  version: ekara
  name: ekara.ssh
