---
- src: https://github.com/lagoon-platform/ansible-role-configuration.git
  version: origin/master
  name: lagoon.configuration

- src: https://github.com/lagoon-platform/ansible-role-ssh-config.git
  version: origin/master
  name: lagoon.ssh
