---
- src: https://github.com/ekara-platform/ansible-role-configuration.git
  version: master
  name: ekara.configuration

- src: https://github.com/ekara-platform/ansible-role-ssh-config.git
  version: master
  name: ekara.ssh

- src: https://github.com/ekara-platform/ansible-role-filesystem.git
  version: master
  name: ekara.filesystem
