---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Checkout roles
    command: ansible-galaxy install -r requirements.yml


- hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
  - name: Load configuration
    include_role:
      name: lagoon.configuration
  tasks:
  - include_role:
      name: aws-cli
    vars:
      aws_region: "{{ lookup('env', 'AWS_REGION') | default('eu-west-1', true) }}"
      aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
  - name: Set Provider
    set_fact:
      lagoon_provider: "{{lagoon_configuration_params.connectionConfig.provider}}"
  - name: Return params for AWS
    template:
      src: templates/output/env.yml
      dest: "{{output_dir}}/env.yaml"
  - name: Add ssh configuration
    include_role:
      name: lagoon.ssh
    vars:
      lagoon_ssh_proxy: "{{ lookup('env', 'http_proxy') }}"
      lagoon_ssh_key: "{{ lagoon_configuration_params.connectionConfig.machine_private_key }}"
      lagoon_ssh_host: '*.amazonaws.com'
    when: lookup('env', 'http_proxy') != ""
