---
- name: Define defaults and mandatory settings for the EC2 security group
  set_fact:
    ek_ec2_current_sg_defaults: >
      {{
        {
          'name': "{{ ek_config.environment.id }}_{{ ek_config.environment.nodeset }}_{{ sg_item.key }}",
          'description': "Security group {{ sg_item.key }} for {{ ek_config.environment.id }}_{{ ek_config.environment.nodeset }}"
        }
      }}
    ek_ec2_current_sg_mandatory: >
      {{
        {
          'region': "{{ ek_aws_region }}",
          'state': 'present',
          'tags': {
            'ek_env_id': "{{ ek_config.environment.id }}",
            'ek_nodeset_id': "{{ ek_config.environment.id }}_{{ ek_config.environment.nodeset }}",
            'ek_nodeset_name': "{{ek_config.environment.nodeset}}"
          }
        }
      }}
- name: Combine security group user settings with default and mandatory settings
  set_fact:
    ek_ec2_current_sg_settings: "{{ ek_ec2_current_sg_defaults | combine(sg_item.value | default({}), recursive=True) | combine(ek_ec2_current_sg_mandatory, recursive=True) }}"
- debug:
    verbosity: 1
    var: ek_ec2_current_sg_settings
- name: Ensure the security group is present
  ec2_group: "{{ ek_ec2_current_sg_settings }}"
  register: ek_ec2_current_sg_info
- name: Store information about the security group
  set_fact:
    ek_ec2_sg_info: "{{ ek_ec2_sg_info | default({}) | combine({sg_item.key: ek_ec2_current_sg_info}, recursive=True) }}"
