---
- name: "Iterating over security group(s)"
  loop: "{{ ek_config.params.securityGroups | dict2items }}"
  loop_control:
    loop_var: sg_item
  include: security-group.yml

- debug:
    verbosity: 1
    var: ek_ec2_sg_info
