---
- name: Create Security groups
  ec2_group:
    name: "{{ekara_configuration_params.environment.id}}_{{ item.name }}"
    description: "sg {{item.name}} for {{ekara_configuration_params.environment.id}}"
    vpc_id: "{{ ekara_configuration_params.params.vpc_id }}"
    rules: "{{item.rules}}"
  loop: "{{ekara_configuration_params.params.security_groups}}"

- set_fact:
    ekara_ec2_group: |
      {% for g in ekara_configuration_params.params.security_groups %}
      {{ekara_configuration_params.environment.id}}_{{ g.name }}
      {% if not loop.last %},{% endif %}{%endfor%}
