---
- name: Create Security groups
  ec2_group:
    name: "{{ekara_configuration_params.environment.name}}_{{ item.name }}_{{ekara_configuration_params.environment.uid}}"
    description: "sg {{item.name}} for {{ekara_configuration_params.environment.name}}"
    vpc_id: "{{ ekara_configuration_params.params.vpc_id }}"
    rules: "{{item.rules}}"
  loop: "{{ekara_configuration_params.params.security_groups}}"

- set_fact:
    ekara_ec2_group: |
      {% for g in ekara_configuration_params.params.security_groups %}
      {{ekara_configuration_params.environment.name}}_{{ g.name }}_{{ekara_configuration_params.environment.uid}}
      {% if not loop.last %},{% endif %}{%endfor%}
