---
- name: Gather instances
  ec2_instance_facts:
    filters:
      "tag:ek.stack_name": "{{ ekara_configuration_params.environment.name }}"
      "tag:ek.stack_qualifier": "{{ ekara_configuration_params.environment.qualifier }}"
      instance-state-name: ['running', 'pending', 'shutting-down', 'stopped', 'stopping']
  register: ekara_instances_plf
- set_fact:
    ekara_instances: "{{ekara_instances_plf.instances|length|int}}"
- name: Gather instances (managers)
  ec2_instance_facts:
    filters:
      "tag:ek.swarm_type": "{{ ekara_plf }}_manager"
      instance-state-name: ['running', 'pending', 'shutting-down', 'stopped', 'stopping']
  register: ekara_instances_managers
- set_fact:
    ekara_instances_managers: "{{ekara_instances_managers.instances|length|int}}"
- debug:
    msg: "{{ekara_instances_managers|int}} manager(s) already exist"
- name: Estimate Swarm managers count
  set_fact:
    ekara_managers: >
      {% set ns = namespace(managers=1) %}{% for x in range(1,([5,(ekara_instances|int)]|min)+1) %}
      {%if x % 2 == 1%}{% set ns.managers = x %}{%endif%}{%endfor%}{{ns.managers}}
- name: Check managers to create
  set_fact:
    ekara_manager_tocreate: "{{ ekara_managers|int - ekara_instances_managers|int }}"
- debug:
    msg: "Add {{ekara_manager_tocreate|int}} managers"

- name: Get new instances to tag
  set_fact:
    ekara_new_instances: "{{ (ekara_new_instances|default([])) + [item] }}"
  loop: "{{ ec2.tagged_instances }}"
  loop_control:
    index_var: index
    label: "{{item.id}}"
  when:
  - ec2.tagged_instances[index].tags['ek.swarm_type'] is not defined

- name: Add swarm tag on new instances
  ec2_tag:
    resource: "{{item.id}}"
    region: "{{item.region}}"
    state: present
    tags:
      ek.swarm_type: "{{ekara_plf}}_{{swarm_type}}"
  vars:
    swarm_type: "{% if index_manager < ekara_manager_tocreate|int %}manager{%else%}worker{%endif%}"
  loop: "{{ekara_new_instances}}"
  loop_control:
    index_var: index_manager
    label: "{{item.id}} - {{item.tags['ek.swarm_type']|default(swarm_type)}}"
