---
- name: Gather all EC2 instance(s)
  ec2_instance_facts:
    filters:
      "tag:ek_env_id": "{{ ek_config.environment.id }}"
      instance-state-name: ['running', 'pending', 'shutting-down', 'stopped', 'stopping']
  register: ekara_instances

- name: "Ensure EC2 instance(s) are absent"
  ec2:
    instance_ids: "{{ ekara_instances | json_query('instances[].instance_id') }}"
    state: absent
    wait: true

- name: "Ensure placement group(s) are absent"
  loop: "{{ ekara_instances | json_query('instances[].placement.group_name') }}"
  ec2_placement_group:
    name: "{{ item }}"
    state: absent
